#!/usr/bin/env bash

# TODO: Swap this

ln_bash() {
    echo "bash -> .bashrc, .bash_profile, .bash_logout"

    ln -sf "$SHELL_DIRECTORY_CONFIG"/home/bash/bashrc "$HOME"/.bashrc        
    ln -sf "$SHELL_DIRECTORY_CONFIG"/home/bash/bash_profile "$HOME"/.bash_profile  
    ln -sf "$SHELL_DIRECTORY_CONFIG"/home/bash/bash_logout "$HOME"/.bash_logout   
}

ln_zsh() {
    echo "zsh -> .zshrc, .zprofile"

    ln -sf "$SHELL_DIRECTORY_CONFIG"/home/zsh/zshrc "$HOME"/.zshrc
    ln -sf "$SHELL_DIRECTORY_CONFIG"/home/zsh/zprofile "$HOME"/.zprofile
}

# Read and print
echo "Home: $HOME"
echo "Shell: $SHELL"
echo "Terminal: $TERM"
echo "Configuration: $SHELL_DIRECTORY_CONFIG"
read -r -p "Are these correct? [y/N] " response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo
    ln_bash
    ln_zsh
fi
