#!/usr/bin/env bash

# List all zsh plugins installed using pacman.

pacman -Qe | grep zsh | awk "{ print $1 }" > "$SHELL_DIRECTORY_CONFIG"/.list
echo "Installed:"
cat "$SHELL_DIRECTORY_CONFIG"/.list
