#
# ~/.zshrc
#

# Load shell profile
source "$HOME"/.config/shell/scripts/main
source "$HOME"/.config/shell/scripts/pretty
source "$HOME"/.config/shell/scripts/rangercd

# History
export ZDOTDIR="$HOME"/.config/zsh

HISTFILE=~/.cache/zhistfile
HISTSIZE=1000
SAVEHIST=1000

# Keybinds
bindkey -s "^B" "tmux new\n"
bindkey -s "^O" "rangercd\n"

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

# Tab completions
autoload -U compinit
zstyle ":completion:*" menu select
zmodload zsh/complist

compinit
_comp_options+=(globdots)

# Prompt
# setopt promptsubst
eval "$(starship init zsh)"

# Plugins
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

plug "zsh-users/zsh-autosuggestions"
plug "hwk929/zsh-fzf"
plug "zsh-users/zsh-history-substring-search"
plug "zsh-users/zsh-syntax-highlighting"
plug "MichaelAquilina/zsh-you-should-use"
