#!/usr/bin/env bash

# Set colors
__PROMPT_RED="\[\e[0;31m\]"
__PROMPT_GREEN="\[\e[0;32m\]"
__PROMPT_YELLOW="\[\e[1;33m\]"
__PROMPT_BLUE="\[\e[1;34m\]"
__PROMPT_CYAN="\[\e[1;36m\]"

__PROMPT_DIR="\w"
__PROMPT_RESET="\[\e[1;39m\]"

source "$HOME"/.config/shell/prompt/ps

# Set prompt
__prompt_exec() {
    __prompt_command
    PS1="$__PROMPT"
}

[ "$BASH_VERSION" ] && PROMPT_COMMAND=__prompt_exec
