#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

# Load shell profile
source "$HOME"/.config/shell/config/main
source "$HOME"/.config/shell/config/scripts/pretty
source "$HOME"/.config/shell/prompt/bash

# Set history
export HISTFILE="$XDG_STATE_HOME"/bash/history
